### **NOR Gate using a Neural Network**

In [17]:
import keras
from keras import models
from keras import layers
from keras import losses 
from keras import optimizers
from keras import metrics 
import numpy as np
import pandas as pd

In [18]:
X = X = np.array([[0,0],[0,1],[1,0],[1,1]], "float32")
Y = np.array([[1],[0],[0],[0]], "float32")

In [20]:
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [21]:
Y

array([[1.],
       [0.],
       [0.],
       [0.]], dtype=float32)

In [22]:
model = models.Sequential()
model.add(layers.Dense(16, input_dim=2, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['binary_accuracy'])

In [23]:
model.fit(X, Y, epochs=200)

Epoch 1/200
1/1 [==============================] - 0s 381ms/step - loss: 0.1526 - binary_accuracy: 0.7500
Epoch 2/200
1/1 [==============================] - 0s 4ms/step - loss: 0.1517 - binary_accuracy: 0.7500
Epoch 3/200
1/1 [==============================] - 0s 8ms/step - loss: 0.1508 - binary_accuracy: 0.7500
Epoch 4/200
1/1 [==============================] - 0s 8ms/step - loss: 0.1499 - binary_accuracy: 0.7500
Epoch 5/200
1/1 [==============================] - 0s 6ms/step - loss: 0.1491 - binary_accuracy: 0.7500
Epoch 6/200
1/1 [==============================] - 0s 10ms/step - loss: 0.1482 - binary_accuracy: 0.7500
Epoch 7/200
1/1 [==============================] - 0s 4ms/step - loss: 0.1474 - binary_accuracy: 0.7500
Epoch 8/200
1/1 [==============================] - 0s 6ms/step - loss: 0.1466 - binary_accuracy: 0.7500
Epoch 9/200
1/1 [==============================] - 0s 7ms/step - loss: 0.1458 - binary_accuracy: 0.7500
Epoch 10/200
1/1 [==============================] - 0s 5ms/st

### **Results**

In [25]:
scores = model.evaluate(X, Y)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

1/1 [==============================] - 0s 91ms/step - loss: 0.0794 - binary_accuracy: 1.0000

binary_accuracy: 100.00%


In [26]:
X1 = np.array([[0,0]])
X2 = np.array([[0,1]])
X3 = np.array([[1,0]])
X4 = np.array([[1,1]])
print("Truth Table\n\n  A B\t\tA NOR B")
print(X1,"\t", model.predict_classes(X1))
print(X2,"\t", model.predict_classes(X2))
print(X3,"\t", model.predict_classes(X3))
print(X4,"\t", model.predict_classes(X4))
print("\n______________________\n")

Truth Table

  A B		A NOR B
[[0 0]] 	 [[1]]
[[0 1]] 	 [[0]]
[[1 0]] 	 [[0]]
[[1 1]] 	 [[0]]

______________________



/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '
